#baseURL = "http://example.org/" #por enquanto não usamos essa configuração
languageCode = "pt-br" #por enquanto não usamos essa configuração
title = "DevOpsDays POA"
theme = "devopsdayspoa"
googleAnalytics = "UA-85374985-3"



[params]
description = "DevOpsDays Porto Alegre - A vida é muito curta para trabalho manual" #irá preencher o meta description
slider = "enable" #qualquer coisa que não seja "enable" irá desabilitar o slider (as imagens que ficam correndo atrás do logo/nome do evento)
slider_selector = "disable" #qualquer coisa que não seja "enable" irá desabilitar os seletores
slider_sidecontrols = "enable" #qualquer coisa que não seja "enable" irá desabilitar os controles
intro_image = "logo.png" #apenas o nome da imagem, deve estar em img/intro/
link_c4p = "https://www.papercall.io/devopsdayspoa2018" #endereço para o form/sistema de call4papers

email = "organizers-porto-alegre-2018@devopsdays.org" #email da organização do email
twitter = "poadevopsday" #para https://www.twitter.com/nao-existe colocar apenas "não-existe"
facebook = "devopsdaypoa" #para https://www.facebook.com/nao-existe colocar apenas "não-existe"

#Os próximos 3 parametros aceitam tags html (ex: <br>) e markdown (ex: **negrito**)
quando = "15 de Setembro"
onde = "Uniritter/FAPA<br />Av. Manoel Elias, 2001<br /> Passo das Pedras, Porto Alegre"
quanto = "Em breve mais informações"

#latitude e longitude podem ser pegos no google maps mesmo :)
#o mapa irá ficar centralizado nessas coordenadas E irá colocar o marcador exatamente sobre elas
mapa_latitude = -30.033101
mapa_longitude = -51.121621
mapa_zoom = 16 #nível de zoom que será apresentado o mapa
mapa_draggable = true #o mapa poderá ser arrastado?
mapa_zoomControl = true #mostrar o controle de zoom?
mapa_scrollwheel = false #a roda de rolagem do mouse deve poder alterar o zoom?
mapa_disableDoubleClickZoom = true #vou ser sincero, não entendi o que isso faz, hahaha
mapa_key = "AIzaSyCZgSdqxA3s-WhsIkB7TLQ4T4Z0Yz3oxH8" #chave na api do google, lembre de permitir o uso no google maps e afins!

status_ingressos = "disponiveis" #qualquer coisa que não seja "disponiveis" irá mostrar o aviso
aviso_status_ingressos = "Em breve!"

status_programacao = "indisponivel" #qualquer coisa que não seja "disponivel" irá mostrar o aviso
aviso_status_programacao = "Em breve! ;)"
